"""
Counterfactual trajectory generation and causal effect estimation for ResistanceMap v6.

This module implements:
1. CounterfactualTrajectoryGenerator: Simulate alternative drug interventions on the
   Neural ODE to answer "what would have happened if we used drug X instead of Y?"
2. WhatIfAnalyzer: Broader counterfactual queries including pathway inhibition,
   treatment timing shifts, and drug combination screening.
3. CausalEffectEstimator: Estimate ATE, CATE, and ITE from the learned structural
   causal model (SCM) via do-calculus interventions.

================================================================
DEPRECATION NOTICE — Bug B4 (v19 roadmap)
================================================================
``WhatIfAnalyzer`` (and the ``do_intervention`` method on
``CausalEffectEstimator``) implement "interventions" by *clamping a latent
ODE dimension at integration time*. This is **associational, not
interventional**, because incoming causal edges into the clamped
dimension remain intact — Pearl's do-operator requires *severing* those
edges, which latent clamping does not do.

For interventional counterfactuals (true do-calculus on the biological
graph), use
``resistancemap.mortfm.causal.counterfactual_simulator.CounterfactualSimulator``
(planned in Phase 8). See ``docs/v18_phase_plan/phase_8_counterfactual.md``
§10 for the identifiability discussion.
================================================================

Key innovation: counterfactual trajectories are generated by modifying the ODE
dynamics, not by retraining. The structured Neural ODE allows surgical interventions
on specific biological programs (e.g., set the drug efflux program to zero) while
preserving the learned dynamics of all other programs.

References:
    Pearl, J. (2009). Causality: Models, Reasoning, and Inference. Cambridge Univ Press.
    Shalit, U. et al. (2017). Estimating individual treatment effect. ICML.
    Bica, I. et al. (2020). Estimating counterfactual treatment outcomes over time. NeurIPS.
    De Brouwer, E. et al. (2019). GRU-ODE-Bayes. NeurIPS.
    Seedat, N. et al. (2022). Continuous-time modeling of counterfactual outcomes. ICML.
"""

from __future__ import annotations

import copy
import warnings
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Optional, Sequence, Tuple, Union

import numpy as np
import torch
import torch.nn as nn
from torch import Tensor


_LATENT_CLAMP_WARNING = (
    "WhatIfAnalyzer uses latent-clamping which is associational, not "
    "interventional. For interventional counterfactuals (true do-calculus on "
    "the biological graph), use "
    "resistancemap.mortfm.causal.counterfactual_simulator.CounterfactualSimulator "
    "(planned in Phase 8). See docs/v18_phase_plan/phase_8_counterfactual.md "
    "§10 for the identifiability discussion."
)

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

@dataclass
class CounterfactualConfig:
    """Configuration for counterfactual analysis.

    Attributes:
        n_trajectory_samples: Number of stochastic trajectory samples for
            uncertainty quantification.
        ode_solver_steps: Number of integration steps for the ODE solver.
        min_intervention_strength: Minimum drug dose to consider.
        max_intervention_strength: Maximum drug dose to consider.
        dose_search_resolution: Number of dose levels to try in dose-response.
        time_search_resolution: Number of time points for optimal timing search.
        convergence_threshold: Threshold for determining trajectory convergence
            to an attractor (resistant vs sensitive).
        combination_max_drugs: Maximum number of drugs in combination search.
        device: Torch device string.
    """
    n_trajectory_samples: int = 100
    ode_solver_steps: int = 200
    min_intervention_strength: float = 0.0
    max_intervention_strength: float = 10.0
    dose_search_resolution: int = 50
    time_search_resolution: int = 50
    convergence_threshold: float = 0.1
    combination_max_drugs: int = 3
    device: str = "cpu"


# ---------------------------------------------------------------------------
# Data containers
# ---------------------------------------------------------------------------

@dataclass
class CounterfactualResult:
    """Container for counterfactual trajectory results.

    Attributes:
        factual_trajectory: (T, D) observed trajectory.
        counterfactual_trajectories: Dict mapping intervention label -> (T, D) trajectory.
        factual_outcome: Scalar outcome under factual scenario.
        counterfactual_outcomes: Dict mapping intervention label -> scalar outcome.
        intervention_details: Dict with metadata about each intervention.
        minimal_intervention: The intervention with smallest magnitude that flips outcome.
        critical_window: (t_start, t_end) of the intervention timing window.
    """
    factual_trajectory: np.ndarray
    counterfactual_trajectories: Dict[str, np.ndarray]
    factual_outcome: float
    counterfactual_outcomes: Dict[str, float]
    intervention_details: Dict[str, Any]
    minimal_intervention: Optional[Dict[str, Any]] = None
    critical_window: Optional[Tuple[float, float]] = None


@dataclass
class CausalEffectResult:
    """Container for causal effect estimation results.

    Attributes:
        ate: Average Treatment Effect across the population.
        cate: Conditional ATE for each subgroup.
        ite: Individual Treatment Effect for each patient.
        confidence_intervals: 95% CI for ATE and CATE.
        subgroup_labels: Labels identifying each subgroup.
    """
    ate: float
    cate: Dict[str, float]
    ite: np.ndarray
    confidence_intervals: Dict[str, Tuple[float, float]]
    subgroup_labels: List[str]


# ---------------------------------------------------------------------------
# Counterfactual Trajectory Generator
# ---------------------------------------------------------------------------

class CounterfactualTrajectoryGenerator:
    """Generate counterfactual trajectories under alternative drug interventions.

    The core idea is that the Neural ODE models patient dynamics as:
        dx/dt = f(x, t) + g(x, drug)
    where f captures autonomous disease dynamics and g captures drug effects.
    By changing the drug term g, we can simulate what would have happened under
    a different treatment without retraining the model.

    Key capabilities:
    - Simulate trajectories under alternative drug interventions
    - Find the MINIMAL intervention that reverses resistance
    - Compute the resistance reversal dose (minimum dose to flip attractor)
    - Find the optimal intervention timing

    Following Bica et al. (2020) "Estimating counterfactual treatment outcomes
    over time using longitudinal data" (NeurIPS) and Seedat et al. (2022)
    "Continuous-time modeling of counterfactual outcomes" (ICML).

    Args:
        model: ResistanceMap Neural ODE model.
        drug_encoder: Module mapping drug identity + dose to intervention vector.
        config: CounterfactualConfig instance.
    """

    def __init__(
        self,
        model: nn.Module,
        drug_encoder: Optional[nn.Module] = None,
        config: Optional[CounterfactualConfig] = None,
    ) -> None:
        self.model = model
        self.drug_encoder = drug_encoder
        self.config = config or CounterfactualConfig()
        self.device = torch.device(self.config.device)
        self.model.to(self.device)
        self.model.eval()

    # ------------------------------------------------------------------
    # Core: simulate counterfactual trajectory
    # ------------------------------------------------------------------

    def simulate_trajectory(
        self,
        x0: Tensor,
        t_span: Tensor,
        drug_id: Optional[int] = None,
        drug_dose: float = 0.0,
        drug_start_time: Optional[float] = None,
        drug_end_time: Optional[float] = None,
    ) -> Tensor:
        """Simulate a trajectory under a specified drug intervention.

        Integrates the modified ODE:
            dx/dt = f(x, t) + drug_effect(x, drug_id, dose) * I(t in [t_start, t_end])

        where I is the indicator function for the treatment window.

        Args:
            x0: Initial state, shape (batch, D) or (D,).
            t_span: Time evaluation points, shape (T,).
            drug_id: Integer drug identifier. None means no drug.
            drug_dose: Drug dosage level.
            drug_start_time: When drug administration begins.
            drug_end_time: When drug administration ends.

        Returns:
            Trajectory tensor of shape (T, batch, D) or (T, D).
        """
        squeeze = x0.dim() == 1
        if squeeze:
            x0 = x0.unsqueeze(0)
        x0 = x0.to(self.device)
        t_span = t_span.to(self.device)

        # Build the drug effect function
        drug_effect_fn = self._build_drug_effect(drug_id, drug_dose)
        t_start = drug_start_time if drug_start_time is not None else t_span[0].item()
        t_end = drug_end_time if drug_end_time is not None else t_span[-1].item()

        # Integrate with modified dynamics
        trajectory = self._integrate_with_intervention(
            x0, t_span, drug_effect_fn, t_start, t_end
        )

        if squeeze:
            trajectory = trajectory.squeeze(1)
        return trajectory.detach().cpu()

    def generate_counterfactuals(
        self,
        x0: Tensor,
        t_span: Tensor,
        factual_drug: Optional[int],
        factual_dose: float,
        alternative_drugs: List[Tuple[Optional[int], float]],
        drug_names: Optional[List[str]] = None,
    ) -> CounterfactualResult:
        """Generate factual and counterfactual trajectories for comparison.

        Args:
            x0: Initial patient state.
            t_span: Time evaluation points.
            factual_drug: The drug actually administered (None for no treatment).
            factual_dose: Actual dosage.
            alternative_drugs: List of (drug_id, dose) tuples for counterfactual scenarios.
            drug_names: Optional human-readable names for drugs.

        Returns:
            CounterfactualResult with all trajectories and outcomes.
        """
        t_span_dev = t_span.to(self.device)

        # Factual trajectory
        factual_traj = self.simulate_trajectory(x0, t_span, factual_drug, factual_dose)
        factual_outcome = self._compute_outcome(factual_traj[-1:])

        # Counterfactual trajectories
        cf_trajectories = {}
        cf_outcomes = {}
        intervention_details = {}

        for i, (drug_id, dose) in enumerate(alternative_drugs):
            name = drug_names[i] if drug_names else f"drug_{drug_id}_dose_{dose:.1f}"
            cf_traj = self.simulate_trajectory(x0, t_span, drug_id, dose)
            cf_outcome = self._compute_outcome(cf_traj[-1:])

            cf_trajectories[name] = cf_traj.numpy()
            cf_outcomes[name] = float(cf_outcome)
            intervention_details[name] = {"drug_id": drug_id, "dose": dose}

        return CounterfactualResult(
            factual_trajectory=factual_traj.numpy(),
            counterfactual_trajectories=cf_trajectories,
            factual_outcome=float(factual_outcome),
            counterfactual_outcomes=cf_outcomes,
            intervention_details=intervention_details,
        )

    # ------------------------------------------------------------------
    # Minimal intervention search
    # ------------------------------------------------------------------

    def find_minimal_intervention(
        self,
        x0: Tensor,
        t_span: Tensor,
        drug_id: int,
        target_outcome: float = 0.0,
    ) -> Dict[str, Any]:
        """Find the minimum drug dose that reverses resistance.

        Uses binary search over dose levels to find the smallest dose that
        pushes the outcome below the resistance threshold.

        The "resistance reversal dose" is clinically meaningful: it tells
        the oncologist the minimum effective dose.

        Args:
            x0: Initial patient state.
            t_span: Time span.
            drug_id: Drug to administer.
            target_outcome: Target outcome threshold (below = sensitive).

        Returns:
            Dict with 'minimal_dose', 'outcome_at_dose', 'dose_response_curve'.
        """
        lo = self.config.min_intervention_strength
        hi = self.config.max_intervention_strength
        n_eval = self.config.dose_search_resolution

        # First, evaluate dose-response curve
        doses = np.linspace(lo, hi, n_eval)
        outcomes = np.zeros(n_eval)

        for i, dose in enumerate(doses):
            traj = self.simulate_trajectory(x0, t_span, drug_id, float(dose))
            outcomes[i] = float(self._compute_outcome(traj[-1:]))

        # Find crossing point
        below_target = outcomes <= target_outcome
        if not below_target.any():
            return {
                "minimal_dose": None,
                "outcome_at_dose": None,
                "dose_response_curve": (doses, outcomes),
                "message": "No dose in range reverses resistance.",
            }

        # Binary search for precise crossing
        first_below = np.argmax(below_target)
        if first_below == 0:
            lo_dose, hi_dose = lo, doses[0]
        else:
            lo_dose, hi_dose = doses[first_below - 1], doses[first_below]

        for _ in range(20):  # 20 iterations of bisection
            mid = (lo_dose + hi_dose) / 2
            traj = self.simulate_trajectory(x0, t_span, drug_id, mid)
            out = float(self._compute_outcome(traj[-1:]))
            if out <= target_outcome:
                hi_dose = mid
            else:
                lo_dose = mid

        minimal_dose = hi_dose
        traj = self.simulate_trajectory(x0, t_span, drug_id, minimal_dose)
        final_outcome = float(self._compute_outcome(traj[-1:]))

        return {
            "minimal_dose": minimal_dose,
            "outcome_at_dose": final_outcome,
            "dose_response_curve": (doses.tolist(), outcomes.tolist()),
        }

    # ------------------------------------------------------------------
    # Time-optimal intervention
    # ------------------------------------------------------------------

    def find_optimal_intervention_time(
        self,
        x0: Tensor,
        t_span: Tensor,
        drug_id: int,
        drug_dose: float,
        target_outcome: float = 0.0,
    ) -> Dict[str, Any]:
        """Find the latest time at which intervention still prevents resistance.

        This answers the critical clinical question: "How long can we wait
        before it's too late to intervene?"

        We simulate trajectories where the drug is administered starting at
        different times and find the latest start time that still achieves
        the target outcome.

        Args:
            x0: Initial patient state.
            t_span: Full time span.
            drug_id: Drug to use.
            drug_dose: Dose to administer.
            target_outcome: Threshold below which the patient is "sensitive."

        Returns:
            Dict with 'latest_effective_time', 'time_outcome_curve',
            and 'critical_window'.
        """
        t_min = t_span[0].item()
        t_max = t_span[-1].item()
        n_eval = self.config.time_search_resolution

        start_times = np.linspace(t_min, t_max * 0.9, n_eval)
        outcomes = np.zeros(n_eval)

        for i, t_start in enumerate(start_times):
            traj = self.simulate_trajectory(
                x0, t_span, drug_id, drug_dose,
                drug_start_time=float(t_start),
            )
            outcomes[i] = float(self._compute_outcome(traj[-1:]))

        # Find the latest time where outcome is still below target
        below_target = outcomes <= target_outcome
        if not below_target.any():
            return {
                "latest_effective_time": None,
                "time_outcome_curve": (start_times.tolist(), outcomes.tolist()),
                "critical_window": None,
                "message": "Intervention at this dose never achieves target.",
            }

        # The critical window is [earliest effective, latest effective]
        effective_times = start_times[below_target]
        earliest = float(effective_times[0])
        latest = float(effective_times[-1])

        return {
            "latest_effective_time": latest,
            "time_outcome_curve": (start_times.tolist(), outcomes.tolist()),
            "critical_window": (earliest, latest),
        }

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _build_drug_effect(
        self,
        drug_id: Optional[int],
        dose: float,
    ) -> Callable[[Tensor, float], Tensor]:
        """Build a callable drug effect function g(x, t) -> dx_drug.

        If a drug_encoder is available, uses it. Otherwise, constructs a
        simple linear drug effect: g(x) = dose * W_drug @ x.

        Args:
            drug_id: Drug identifier.
            dose: Drug dosage.

        Returns:
            Callable taking (x, t) and returning drug-induced velocity.
        """
        if drug_id is None or dose == 0.0:
            return lambda x, t: torch.zeros_like(x)

        if self.drug_encoder is not None:
            drug_tensor = torch.tensor([drug_id], device=self.device)
            dose_tensor = torch.tensor([dose], device=self.device, dtype=torch.float32)

            def effect(x: Tensor, t: float) -> Tensor:
                with torch.no_grad():
                    return self.drug_encoder(x, drug_tensor, dose_tensor)
            return effect

        # Fallback: use model's drug_effect if available
        if hasattr(self.model, "drug_effect"):
            def effect(x: Tensor, t: float) -> Tensor:
                return self.model.drug_effect(x, drug_id, dose)
            return effect

        # Minimal fallback: perturbation proportional to dose
        def effect(x: Tensor, t: float) -> Tensor:
            return -dose * 0.1 * x
        return effect

    def _integrate_with_intervention(
        self,
        x0: Tensor,
        t_eval: Tensor,
        drug_effect_fn: Callable,
        t_start: float,
        t_end: float,
    ) -> Tensor:
        """Euler integration of modified ODE with drug intervention.

        dx/dt = f(x, t) + g(x, t) * I(t_start <= t <= t_end)

        Args:
            x0: Initial state (batch, D).
            t_eval: Time points to evaluate.
            drug_effect_fn: Drug effect function g(x, t).
            t_start: Treatment start time.
            t_end: Treatment end time.

        Returns:
            Trajectory tensor (T, batch, D).
        """
        trajectory = [x0]
        x = x0.clone()

        for i in range(1, len(t_eval)):
            t = t_eval[i - 1]
            dt = (t_eval[i] - t_eval[i - 1]).item()

            # Autonomous dynamics
            with torch.no_grad():
                dxdt = self._ode_rhs(x, t)

            # Drug effect (only within treatment window)
            t_val = t.item() if isinstance(t, Tensor) else t
            if t_start <= t_val <= t_end:
                with torch.no_grad():
                    dxdt = dxdt + drug_effect_fn(x, t_val)

            x = x + dt * dxdt
            trajectory.append(x.clone())

        return torch.stack(trajectory)

    def _ode_rhs(self, x: Tensor, t: Tensor) -> Tensor:
        """Evaluate ODE right-hand side."""
        if hasattr(self.model, "ode_func"):
            return self.model.ode_func(t, x)
        raise RuntimeError("Model must expose .ode_func(t, x).")

    def _compute_outcome(self, x: Tensor) -> Tensor:
        """Compute resistance outcome from state."""
        if x.dim() == 3:
            x = x.squeeze(0)
        if hasattr(self.model, "predict"):
            with torch.no_grad():
                return self.model.predict(x).mean()
        if hasattr(self.model, "classifier"):
            with torch.no_grad():
                return torch.sigmoid(self.model.classifier(x)).mean()
        return x.norm(dim=-1).mean()


# ---------------------------------------------------------------------------
# WhatIfAnalyzer
# ---------------------------------------------------------------------------

class WhatIfAnalyzer:
    """ASSOCIATIONAL ONLY — not a do-calculus implementation.

    Broader counterfactual reasoning over the Neural ODE.

    Supports:
    - Pathway inhibition: "What if we knock out the PI3K/AKT pathway?"
    - Treatment timing: "What if we started treatment 2 months earlier?"
    - Drug combinations: "What combination of drugs achieves synergy?"

    Each query modifies the ODE dynamics by *clamping a latent state
    dimension* at integration time. This is **associational** (effectively
    a covariate intervention on the latent trajectory) and is NOT a
    Pearl-do operation, because incoming causal edges into the clamped
    dimension remain intact rather than being severed.

    For real do-calculus counterfactuals on the biological graph, use
    ``resistancemap.mortfm.causal.counterfactual_simulator.CounterfactualSimulator``
    (planned in Phase 8). See ``docs/v18_phase_plan/phase_8_counterfactual.md``
    §10 for the identifiability discussion.

    Args:
        model: ResistanceMap Neural ODE.
        program_names: Names of the biological programs (latent dimensions).
        cf_generator: CounterfactualTrajectoryGenerator for simulation.
        config: CounterfactualConfig.
    """

    def __init__(
        self,
        model: nn.Module,
        program_names: List[str],
        cf_generator: Optional[CounterfactualTrajectoryGenerator] = None,
        config: Optional[CounterfactualConfig] = None,
    ) -> None:
        warnings.warn(_LATENT_CLAMP_WARNING, DeprecationWarning, stacklevel=2)
        self.model = model
        self.program_names = program_names
        self.program_to_idx = {name: i for i, name in enumerate(program_names)}
        self.config = config or CounterfactualConfig()
        self.device = torch.device(self.config.device)

        if cf_generator is not None:
            self.cf_gen = cf_generator
        else:
            self.cf_gen = CounterfactualTrajectoryGenerator(model, config=self.config)

    def inhibit_pathway(
        self,
        x0: Tensor,
        t_span: Tensor,
        pathway_name: str,
        inhibition_strength: float = 1.0,
    ) -> Dict[str, Any]:
        """Simulate trajectory with a specific pathway/program inhibited.

        Sets the corresponding dimension of the ODE state to zero (full
        inhibition) or reduces it (partial inhibition) at each integration step.

        This corresponds to a perfect pathway inhibitor drug with instantaneous
        action: do(program_k = 0).

        Args:
            x0: Initial state.
            t_span: Time span.
            pathway_name: Name of the biological program to inhibit.
            inhibition_strength: 0.0 = no inhibition, 1.0 = full knockout.

        Returns:
            Dict with 'inhibited_trajectory', 'baseline_trajectory',
            'outcome_change', 'program_idx'.
        """
        warnings.warn(_LATENT_CLAMP_WARNING, DeprecationWarning, stacklevel=2)
        if pathway_name not in self.program_to_idx:
            raise ValueError(
                f"Unknown program: {pathway_name}. "
                f"Available: {list(self.program_to_idx.keys())}"
            )

        prog_idx = self.program_to_idx[pathway_name]

        if x0.dim() == 1:
            x0 = x0.unsqueeze(0)
        x0 = x0.to(self.device)
        t_span = t_span.to(self.device)

        # Baseline trajectory (no inhibition)
        with torch.no_grad():
            baseline_traj = self._solve_ode(x0, t_span)

        # Inhibited trajectory: clamp program dimension at each step
        inhibited_traj = [x0.clone()]
        x = x0.clone()
        for i in range(1, len(t_span)):
            dt = (t_span[i] - t_span[i - 1]).item()
            with torch.no_grad():
                dxdt = self._ode_rhs(x, t_span[i - 1])
            x = x + dt * dxdt
            # Apply inhibition: reduce the target program dimension
            x_new = x.clone()
            x_new[:, prog_idx] = x[:, prog_idx] * (1.0 - inhibition_strength)
            x = x_new
            inhibited_traj.append(x.clone())
        inhibited_traj = torch.stack(inhibited_traj)

        # Compute outcomes
        baseline_out = float(self._compute_outcome(baseline_traj[-1:]))
        inhibited_out = float(self._compute_outcome(inhibited_traj[-1:]))

        return {
            "inhibited_trajectory": inhibited_traj.squeeze(1).detach().cpu().numpy(),
            "baseline_trajectory": baseline_traj.squeeze(1).detach().cpu().numpy(),
            "baseline_outcome": baseline_out,
            "inhibited_outcome": inhibited_out,
            "outcome_change": inhibited_out - baseline_out,
            "program_idx": prog_idx,
            "pathway_name": pathway_name,
            "inhibition_strength": inhibition_strength,
        }

    def shift_treatment_timing(
        self,
        x0: Tensor,
        t_span: Tensor,
        drug_id: int,
        drug_dose: float,
        original_start: float,
        time_shifts: List[float],
    ) -> Dict[str, Any]:
        """Simulate trajectories with treatment starting at different times.

        Answers: "What if we had started treatment N months earlier/later?"

        Args:
            x0: Initial state.
            t_span: Time span.
            drug_id: Drug identifier.
            drug_dose: Drug dosage.
            original_start: Original treatment start time.
            time_shifts: List of time deltas (negative = earlier, positive = later).

        Returns:
            Dict mapping shift label -> trajectory and outcome.
        """
        results = {}

        for shift in time_shifts:
            new_start = max(original_start + shift, t_span[0].item())
            label = f"shift_{shift:+.1f}"

            traj = self.cf_gen.simulate_trajectory(
                x0, t_span, drug_id, drug_dose,
                drug_start_time=new_start,
            )
            outcome = float(self._compute_outcome(traj[-1:]))

            results[label] = {
                "trajectory": traj.numpy(),
                "outcome": outcome,
                "treatment_start": new_start,
                "time_shift": shift,
            }

        return results

    def screen_drug_combinations(
        self,
        x0: Tensor,
        t_span: Tensor,
        drug_ids: List[int],
        drug_doses: List[float],
        drug_names: Optional[List[str]] = None,
    ) -> Dict[str, Any]:
        """Screen drug pairs/triplets for synergistic effects.

        For each pair of drugs, simulate the combined trajectory and compare
        to individual drug trajectories. Synergy is defined using Bliss
        independence:
            synergy = E_AB - E_A * E_B
        where E is the efficacy (reduction in resistance outcome).

        Args:
            x0: Initial state.
            t_span: Time span.
            drug_ids: List of drug identifiers to screen.
            drug_doses: Corresponding doses.
            drug_names: Optional human-readable names.

        Returns:
            Dict with 'individual_outcomes', 'combination_outcomes',
            'synergy_scores', 'best_combination'.
        """
        n_drugs = len(drug_ids)
        if drug_names is None:
            drug_names = [f"drug_{d}" for d in drug_ids]

        # No-treatment baseline
        baseline_traj = self.cf_gen.simulate_trajectory(x0, t_span)
        baseline_outcome = float(self._compute_outcome(baseline_traj[-1:]))

        # Individual drug outcomes
        individual = {}
        for drug_id, dose, name in zip(drug_ids, drug_doses, drug_names):
            traj = self.cf_gen.simulate_trajectory(x0, t_span, drug_id, dose)
            outcome = float(self._compute_outcome(traj[-1:]))
            efficacy = max(0, baseline_outcome - outcome) / max(baseline_outcome, 1e-8)
            individual[name] = {"outcome": outcome, "efficacy": efficacy}

        # Drug pair combinations
        combination_outcomes = {}
        synergy_scores = {}

        max_combo = min(self.config.combination_max_drugs, n_drugs)
        from itertools import combinations

        for r in range(2, max_combo + 1):
            for combo_idx in combinations(range(n_drugs), r):
                combo_name = " + ".join(drug_names[i] for i in combo_idx)

                # Simulate combined effect by summing drug effects
                # This is done by sequential simulation with cumulative interventions
                traj = self._simulate_combination(
                    x0, t_span,
                    [drug_ids[i] for i in combo_idx],
                    [drug_doses[i] for i in combo_idx],
                )
                outcome = float(self._compute_outcome(traj[-1:]))
                combo_efficacy = max(0, baseline_outcome - outcome) / max(baseline_outcome, 1e-8)

                combination_outcomes[combo_name] = {
                    "outcome": outcome,
                    "efficacy": combo_efficacy,
                }

                # Bliss independence for synergy
                indiv_efficacies = [individual[drug_names[i]]["efficacy"] for i in combo_idx]
                expected_indep = 1.0
                for e in indiv_efficacies:
                    expected_indep *= (1.0 - e)
                expected_efficacy = 1.0 - expected_indep

                synergy = combo_efficacy - expected_efficacy
                synergy_scores[combo_name] = synergy

        # Find best combination
        if synergy_scores:
            best = max(synergy_scores, key=synergy_scores.get)
        else:
            best = None

        return {
            "baseline_outcome": baseline_outcome,
            "individual_outcomes": individual,
            "combination_outcomes": combination_outcomes,
            "synergy_scores": synergy_scores,
            "best_combination": best,
        }

    def _simulate_combination(
        self,
        x0: Tensor,
        t_span: Tensor,
        drug_ids: List[int],
        drug_doses: List[float],
    ) -> Tensor:
        """Simulate trajectory under multiple concurrent drugs.

        Sums the drug effects from each drug at each integration step.
        """
        if x0.dim() == 1:
            x0 = x0.unsqueeze(0)
        x0 = x0.to(self.device)
        t_span = t_span.to(self.device)

        drug_effects = [
            self.cf_gen._build_drug_effect(did, dose)
            for did, dose in zip(drug_ids, drug_doses)
        ]

        trajectory = [x0]
        x = x0.clone()
        for i in range(1, len(t_span)):
            dt = (t_span[i] - t_span[i - 1]).item()
            with torch.no_grad():
                dxdt = self._ode_rhs(x, t_span[i - 1])
                for eff in drug_effects:
                    dxdt = dxdt + eff(x, t_span[i - 1].item())
            x = x + dt * dxdt
            trajectory.append(x.clone())

        return torch.stack(trajectory).detach().cpu()

    # ------------------------------------------------------------------
    # Shared helpers
    # ------------------------------------------------------------------

    def _solve_ode(self, x0: Tensor, t_eval: Tensor) -> Tensor:
        if hasattr(self.model, "solve"):
            return self.model.solve(x0, t_eval)
        try:
            from torchdiffeq import odeint
            return odeint(self.model.ode_func, x0, t_eval)
        except ImportError:
            # Euler fallback
            traj = [x0]
            x = x0
            for i in range(1, len(t_eval)):
                dt = (t_eval[i] - t_eval[i - 1]).item()
                x = x + dt * self._ode_rhs(x, t_eval[i - 1])
                traj.append(x)
            return torch.stack(traj)

    def _ode_rhs(self, x: Tensor, t: Tensor) -> Tensor:
        if hasattr(self.model, "ode_func"):
            return self.model.ode_func(t, x)
        raise RuntimeError("Model must expose .ode_func(t, x).")

    def _compute_outcome(self, x: Tensor) -> Tensor:
        if x.dim() == 3:
            x = x.squeeze(0)
        if hasattr(self.model, "predict"):
            with torch.no_grad():
                return self.model.predict(x).mean()
        if hasattr(self.model, "classifier"):
            with torch.no_grad():
                return torch.sigmoid(self.model.classifier(x)).mean()
        return x.norm(dim=-1).mean()


# ---------------------------------------------------------------------------
# Causal Effect Estimator
# ---------------------------------------------------------------------------

class CausalEffectEstimator:
    """Estimate treatment effects from the learned structural causal model.

    The causal fusion layer in ResistanceMap encodes the hierarchy:
        genetic -> epigenetic -> transcriptomic -> proteomic

    We can perform do-calculus interventions (Pearl, 2009) on any layer
    to estimate the causal effect of treatments.

    Implements:
    - ATE: Average Treatment Effect = E[Y(1)] - E[Y(0)]
    - CATE: Conditional ATE = E[Y(1) - Y(0) | X = x] for subgroups
    - ITE: Individual Treatment Effect = Y_i(1) - Y_i(0) for each patient

    Following Shalit et al. (2017) "Estimating individual treatment effect:
    generalization bounds and algorithms" (ICML).

    Args:
        model: ResistanceMap model with causal fusion layer.
        config: CounterfactualConfig.
    """

    def __init__(
        self,
        model: nn.Module,
        config: Optional[CounterfactualConfig] = None,
    ) -> None:
        self.model = model
        self.config = config or CounterfactualConfig()
        self.device = torch.device(self.config.device)
        self.model.to(self.device)
        self.model.eval()

    def estimate_ate(
        self,
        patient_states: Tensor,
        t_span: Tensor,
        treatment_drug: int,
        treatment_dose: float,
        control_drug: Optional[int] = None,
        control_dose: float = 0.0,
    ) -> Dict[str, Any]:
        """Estimate the Average Treatment Effect (ATE).

        ATE = E[Y(treatment)] - E[Y(control)]

        Uses the Neural ODE to simulate both treated and control trajectories
        for each patient, then averages the difference.

        Args:
            patient_states: (N, D) tensor of patient initial states.
            t_span: Time span for simulation.
            treatment_drug: Drug ID for treatment arm.
            treatment_dose: Dose for treatment arm.
            control_drug: Drug ID for control arm (None = no treatment).
            control_dose: Dose for control arm.

        Returns:
            Dict with 'ate', 'ate_ci', 'ite' (individual effects),
            and 'treated_outcomes', 'control_outcomes'.
        """
        N = patient_states.shape[0]
        cf_gen = CounterfactualTrajectoryGenerator(self.model, config=self.config)

        treated_outcomes = np.zeros(N)
        control_outcomes = np.zeros(N)

        for i in range(N):
            x0_i = patient_states[i]

            # Treated trajectory
            traj_t = cf_gen.simulate_trajectory(x0_i, t_span, treatment_drug, treatment_dose)
            treated_outcomes[i] = float(self._compute_outcome(traj_t[-1:]))

            # Control trajectory
            traj_c = cf_gen.simulate_trajectory(x0_i, t_span, control_drug, control_dose)
            control_outcomes[i] = float(self._compute_outcome(traj_c[-1:]))

        ite = treated_outcomes - control_outcomes
        ate = float(np.mean(ite))

        # Bootstrap confidence interval
        n_bootstrap = 1000
        boot_ates = np.zeros(n_bootstrap)
        for b in range(n_bootstrap):
            idx = np.random.choice(N, size=N, replace=True)
            boot_ates[b] = np.mean(ite[idx])
        ci_lo = float(np.percentile(boot_ates, 2.5))
        ci_hi = float(np.percentile(boot_ates, 97.5))

        return {
            "ate": ate,
            "ate_ci": (ci_lo, ci_hi),
            "ite": ite,
            "treated_outcomes": treated_outcomes,
            "control_outcomes": control_outcomes,
        }

    def estimate_cate(
        self,
        patient_states: Tensor,
        t_span: Tensor,
        treatment_drug: int,
        treatment_dose: float,
        subgroup_labels: np.ndarray,
        control_drug: Optional[int] = None,
        control_dose: float = 0.0,
    ) -> CausalEffectResult:
        """Estimate Conditional Average Treatment Effect (CATE) per subgroup.

        CATE_g = E[Y(1) - Y(0) | G = g]

        Subgroups might be defined by genetic subtypes, disease stage, or
        prior treatment history.

        Args:
            patient_states: (N, D) tensor of patient states.
            t_span: Time span.
            treatment_drug: Drug ID for treatment.
            treatment_dose: Dose for treatment.
            subgroup_labels: (N,) array of subgroup assignments.
            control_drug: Drug ID for control.
            control_dose: Dose for control.

        Returns:
            CausalEffectResult with ATE, CATE, ITE, and CIs.
        """
        ate_result = self.estimate_ate(
            patient_states, t_span, treatment_drug, treatment_dose,
            control_drug, control_dose,
        )
        ite = ate_result["ite"]

        unique_groups = sorted(set(subgroup_labels))
        cate = {}
        cis = {"ate": ate_result["ate_ci"]}

        for g in unique_groups:
            mask = subgroup_labels == g
            group_ite = ite[mask]
            cate[str(g)] = float(np.mean(group_ite))

            # Bootstrap CI for this subgroup
            n_boot = 1000
            n_g = mask.sum()
            boot = np.zeros(n_boot)
            for b in range(n_boot):
                idx = np.random.choice(n_g, size=n_g, replace=True)
                boot[b] = np.mean(group_ite[idx])
            cis[str(g)] = (float(np.percentile(boot, 2.5)),
                           float(np.percentile(boot, 97.5)))

        return CausalEffectResult(
            ate=ate_result["ate"],
            cate=cate,
            ite=ite,
            confidence_intervals=cis,
            subgroup_labels=[str(g) for g in unique_groups],
        )

    def do_intervention(
        self,
        x0: Tensor,
        t_span: Tensor,
        layer_name: str,
        intervention_values: Tensor,
    ) -> Tensor:
        """Perform a do-calculus intervention on the causal fusion layer.

        Implements do(layer = value) by clamping the specified layer's output
        to the intervention values during forward pass.

        The causal hierarchy is: genetic -> epigenetic -> transcriptomic -> proteomic.
        Intervening on an upstream layer propagates effects downstream.

        Args:
            x0: Initial state.
            t_span: Time span.
            layer_name: Name of the causal layer to intervene on.
            intervention_values: Values to clamp the layer to.

        Returns:
            Intervened trajectory tensor.
        """
        warnings.warn(_LATENT_CLAMP_WARNING, DeprecationWarning, stacklevel=2)
        if x0.dim() == 1:
            x0 = x0.unsqueeze(0)
        x0 = x0.to(self.device)
        t_span = t_span.to(self.device)
        intervention_values = intervention_values.to(self.device)

        # Create a modified model with the intervention
        model_copy = copy.deepcopy(self.model)

        # Register a forward hook on the target layer to clamp output
        target_layer = None
        for name, module in model_copy.named_modules():
            if layer_name in name:
                target_layer = module
                break

        if target_layer is None:
            raise ValueError(
                f"Layer '{layer_name}' not found. Available: "
                f"{[n for n, _ in model_copy.named_modules()]}"
            )

        def clamp_hook(module, input, output):
            return intervention_values.expand_as(output)

        handle = target_layer.register_forward_hook(clamp_hook)

        # Simulate with intervened model
        try:
            if hasattr(model_copy, "solve"):
                trajectory = model_copy.solve(x0, t_span)
            else:
                trajectory = self._euler_solve(model_copy, x0, t_span)
        finally:
            handle.remove()

        return trajectory.detach().cpu()

    def _euler_solve(self, model: nn.Module, x0: Tensor, t_eval: Tensor) -> Tensor:
        traj = [x0]
        x = x0
        for i in range(1, len(t_eval)):
            dt = (t_eval[i] - t_eval[i - 1]).item()
            dxdt = model.ode_func(t_eval[i - 1], x)
            x = x + dt * dxdt
            traj.append(x)
        return torch.stack(traj)

    def _compute_outcome(self, x: Tensor) -> Tensor:
        if x.dim() == 3:
            x = x.squeeze(0)
        if hasattr(self.model, "predict"):
            with torch.no_grad():
                return self.model.predict(x).mean()
        if hasattr(self.model, "classifier"):
            with torch.no_grad():
                return torch.sigmoid(self.model.classifier(x)).mean()
        return x.norm(dim=-1).mean()


# ---------------------------------------------------------------------------
# Unit tests
# ---------------------------------------------------------------------------

def _test_counterfactual_engine():
    """Unit tests for counterfactual trajectory generation."""
    print("Running counterfactual engine tests...")

    # --- Mock model ---
    class MockODEFunc(nn.Module):
        def __init__(self, dim):
            super().__init__()
            self.A = nn.Parameter(torch.randn(dim, dim) * 0.05)

        def forward(self, t, x):
            return x @ self.A

    class MockModel(nn.Module):
        def __init__(self, dim):
            super().__init__()
            self.ode_func = MockODEFunc(dim)
            self.classifier = nn.Linear(dim, 1)

        def solve(self, x0, t_eval):
            traj = [x0]
            x = x0
            for i in range(1, len(t_eval)):
                dt = (t_eval[i] - t_eval[i - 1]).item()
                x = x + dt * self.ode_func(t_eval[i], x)
                traj.append(x)
            return torch.stack(traj)

        def predict(self, x):
            return torch.sigmoid(self.classifier(x))

    dim = 8
    model = MockModel(dim)
    config = CounterfactualConfig(dose_search_resolution=10, time_search_resolution=10)

    # Test CounterfactualTrajectoryGenerator
    cf_gen = CounterfactualTrajectoryGenerator(model, config=config)

    x0 = torch.randn(dim)
    t_span = torch.linspace(0, 1, 20)

    # Simulate single trajectory
    traj = cf_gen.simulate_trajectory(x0, t_span, drug_id=1, drug_dose=1.0)
    assert traj.shape == (20, dim), f"Expected (20, {dim}), got {traj.shape}"
    print(f"  Single trajectory shape: {traj.shape} -- PASS")

    # Generate counterfactuals
    result = cf_gen.generate_counterfactuals(
        x0, t_span,
        factual_drug=None, factual_dose=0.0,
        alternative_drugs=[(1, 1.0), (2, 2.0)],
        drug_names=["venetoclax", "bortezomib"],
    )
    assert isinstance(result, CounterfactualResult)
    assert "venetoclax" in result.counterfactual_trajectories
    print(f"  Counterfactuals: {list(result.counterfactual_outcomes.keys())} -- PASS")

    # Minimal intervention
    mi = cf_gen.find_minimal_intervention(x0, t_span, drug_id=1)
    assert "dose_response_curve" in mi
    print(f"  Minimal intervention search: {mi.get('minimal_dose', 'N/A')} -- PASS")

    # Optimal timing
    ot = cf_gen.find_optimal_intervention_time(x0, t_span, drug_id=1, drug_dose=2.0)
    assert "time_outcome_curve" in ot
    print(f"  Optimal timing: {ot.get('latest_effective_time', 'N/A')} -- PASS")

    # Test WhatIfAnalyzer
    programs = ["stemness", "drug_efflux", "dna_damage", "immune_evasion",
                "metabolic", "epigenetic", "proliferation", "apoptosis"]
    wia = WhatIfAnalyzer(model, programs, cf_gen, config)

    inhib = wia.inhibit_pathway(x0, t_span, "drug_efflux", 0.5)
    assert "inhibited_trajectory" in inhib
    print(f"  Pathway inhibition: outcome change={inhib['outcome_change']:.4f} -- PASS")

    timing = wia.shift_treatment_timing(
        x0, t_span, drug_id=1, drug_dose=1.0,
        original_start=0.5, time_shifts=[-0.2, 0.0, 0.2],
    )
    assert len(timing) == 3
    print(f"  Treatment timing shifts: {len(timing)} scenarios -- PASS")

    combos = wia.screen_drug_combinations(
        x0, t_span, drug_ids=[1, 2, 3], drug_doses=[1.0, 1.0, 1.0],
        drug_names=["ven", "bort", "dex"],
    )
    assert "synergy_scores" in combos
    print(f"  Drug combinations: best={combos['best_combination']} -- PASS")

    # Test CausalEffectEstimator
    cee = CausalEffectEstimator(model, config)
    patients = torch.randn(10, dim)
    ate_res = cee.estimate_ate(patients, t_span, treatment_drug=1, treatment_dose=1.0)
    assert "ate" in ate_res
    print(f"  ATE estimate: {ate_res['ate']:.4f}, CI={ate_res['ate_ci']} -- PASS")

    labels = np.array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1])
    cate_res = cee.estimate_cate(
        patients, t_span, treatment_drug=1, treatment_dose=1.0,
        subgroup_labels=labels,
    )
    assert isinstance(cate_res, CausalEffectResult)
    print(f"  CATE: {cate_res.cate} -- PASS")

    print("All counterfactual engine tests PASSED.\n")


if __name__ == "__main__":
    _test_counterfactual_engine()
